[project]
name = "mlops-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mlflow>=3.7.0",
    "pandas>=2.3.3",
    "titanic",
]

[tool.uv.sources]
titanic = { path = "../Titanic/dist/titanic-0.1.0-py3-none-any.whl" }
